TOPDIR          = /home/u12066/local/local.x86_64/src/omnirpc
MKRULESDIR      = /home/u12066/local/local.x86_64/src/omnirpc/mk

include $(MKRULESDIR)/vars.mk

DIRS	=	QC_API qcrex qcmeasure

include $(MKRULESDIR)/rules.mk
