Module qc_qasm;

Globals{
#include "omni_platform.h"
#include "qcs_api.hpp"
#ifdef HAVE_SlURM
#include "slurm/slurm.h"
#include "slurm/slurm_errno.h"
#endif /* HAVE_SLURM */
  
#include "qcrex_conf.h"  
}

Define qc_rpc_qasm(/* 0 */ IN int dlen,
		   /* 1 */ IN char d[dlen],
		   /* 2 */ IN int qlen,
		   /* 3 */ IN char q[qlen],
		   /* 4 */ OUT int ret[],
		   /* 5 */ IN int snum,
		   /* 6 */ OUT int sidx[snum],
		   /* 7 */ OUT double sval[snum],
		   /* 8 */ OUT int n_shots[])
"QC RPC QASM_STUB"
{
  int i;
  
  fprintf(stderr, "stub qc_rpc_qasm():%s: started.\n", __func__);

  if (d != NULL && *d != '\0' &&
      chdir(d) == 0 &&
      q != NULL && *q != '\0') {
    char cmd[65536];

    *ret = INT_MAX;

    fprintf(stderr, "directory: %s\n", d);
    fprintf(stderr, "QASM: %s/%s\n", d, q);

    snprintf(cmd, sizeof(cmd), "%s %s %s", QURIWRAPPER, d, q);
    *ret = system(cmd);

    if (*ret >= 0) {
      *n_shots = (snum < 10) ? snum : 10;

      for (i = 0; i < *n_shots; i++) {
	sidx[i] = i + 2;
	sval[i] = (double)i * 3;
      }
    } else {
      (void)memset(sidx, 0, sizeof(int) * *n_shots);
      (void)memset(sval, 0, sizeof(double) * *n_shots);
    }
  }

  fprintf(stderr, "stub qc_rpc_qasm():%s: finished.\n", __func__);
}
